# Generated by Django 6.0.1 on 2026-02-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
