# Generated by Django 6.0.1 on 2026-02-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_alter_menu_created_at_alter_menu_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("FLAT", "Flat"), ("PERCENTAGE", "Percentage")],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "restaurant_specific",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specific_coupons",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
        ),
    ]
