# Generated by Django 6.0.1 on 2026-02-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(null=True),
        ),
    ]
