# Generated by Django 6.0.1 on 2026-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_alter_coupon_valid_from_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
