# Generated by Django 6.0.1 on 2026-02-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(
                db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("PAID", "paid"),
                    ("FAILED", "failed"),
                    ("CANCELLED", "cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
