# Generated by Django 6.0.1 on 2026-02-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_razorpay_order_id_order_razorpay_payment_id_and_more"),
        ("payments", "0006_rename_cart_payment_carts"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="payments.payment",
            ),
        ),
    ]
