# Generated by Django 6.0.1 on 2026-02-25 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_reportcheckpoint"),
        ("restaurants", "0005_alter_coupon_valid_from_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurants.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discounted_applied",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
