# Generated by Django 6.0.1 on 2026-02-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_cart_restaurant_alter_cart_user_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="carts",
            field=models.ManyToManyField(related_name="payments", to="orders.cart"),
        ),
    ]
