# Generated by Django 6.0.1 on 2026-02-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_cart_unique_together_and_more"),
        ("payments", "0002_payment_carts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="razorpay_payment_id",
            new_name="payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="carts",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_payment_link_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="cart",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="orders.cart",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(default="razorpay", max_length=50),
        ),
    ]
