# Generated by Django 6.0.1 on 2026-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_cart_unique_together_and_more"),
        ("payments", "0003_rename_razorpay_payment_id_payment_payment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="cart",
        ),
        migrations.AddField(
            model_name="payment",
            name="cart",
            field=models.ManyToManyField(
                null=True, related_name="payment", to="orders.cart"
            ),
        ),
    ]
