# Generated by Django 6.0.1 on 2026-02-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_cart_user"),
        ("payments", "0003_payment_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.cart",
            ),
        ),
    ]
