# Generated by Django 6.0.1 on 2026-02-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_cart_user"),
        ("payments", "0004_payment_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_id",
            new_name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_link_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name="payment",
            name="cart",
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(default="razorpay", max_length=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="INITIATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="cart",
            field=models.ManyToManyField(related_name="payment", to="orders.cart"),
        ),
    ]
