# Generated by Django 6.0.1 on 2026-02-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_remove_payment_cart_payment_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="cart",
            new_name="carts",
        ),
    ]
