# Generated by Django 6.0.1 on 2026-02-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_cart_unique_together_and_more"),
        ("payments", "0005_rename_cart_payment_carts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="carts",
            field=models.ManyToManyField(related_name="payment", to="orders.cart"),
        ),
    ]
