# Generated by Django 6.0.1 on 2026-02-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_rename_payment_id_payment_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="cart",
            new_name="carts",
        ),
    ]
