# Generated by Django 6.0.1 on 2026-02-25 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_payment_carts"),
        ("restaurants", "0005_alter_coupon_valid_from_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="restaurants.coupon",
            ),
        ),
    ]
